/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fjaohfebbidrsitqitbm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqYW9oZmViYmlkcnNpdHFpdGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA3ODIwMjIsImV4cCI6MjA5NjM1ODAyMn0.-uEeIhpr_cxsPogIBdqih4z5-6S2PLFVJNoIKx-z8NU"